 
services: 

  redis:
    container_name: redis
    restart: always
    ports:
        - 6379:6379
    environment:
          - REDIS_PASSWORD=1234
          - REDIS_PORT=6379
    image: redis:6.0-alpine
    # command: redis-server --loglevel warning
    volumes:
        - redis_data:/root/redis
        # - ./config:/usr/local/etc/redis/redis.conf
    networks:
        - edu
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5


  worker1:
    container_name: worker1
    build: .
    # command: celery -A core worker --loglevel=info
    command: celery -A core.celery worker --pool=prefork --concurrency=5 --autoscale=10,3 -l info && celery -A core beat -l info

    env_file: .env
    networks:
        - edu
    volumes:
      - ./core:/app
    depends_on:
      - backend1
      - redis

  backend1:
    build: .
    container_name: backend1
    command: python manage.py runserver 0.0.0.0:8000
    # command: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput gunicorn -w 8 core.wsgi:application --bind 0.0.0.0:8000
    # command: daphne core.asgi:application --bind 0.0.0.0 -p 8000
    # command: "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    # command: "gunicorn -b 0.0.0.0:8000 core.wsgi:application --workers 8"
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DEBUG=False
    restart: always
    networks:
        - edu
    depends_on:
      - redis
      - db
    # networks:
    #   - nginxnetwork
  

  db:
    restart: always
    env_file: .env
    image: postgres:14 
    container_name: db
    volumes:
      - mydb:/var/lib/postgresql/data
    networks:
        - edu
    ports:
      - "5434:5432"
    # networks:
    #   - postgresnetwork
 

 

 
#   master:
#     image: locustio/locust
#     ports:
#      - "8089:8089"
#     restart: always
#     volumes:
#       - ./locust:/mnt/locust
#     command: -f /mnt/locust/locustfile.py  --master -H http://127.0.0.1:80/
  
#   worker:
#     image: locustio/locust
#     restart: always
#     volumes:
#       - ./locust:/mnt/locust
#     command: -f /mnt/locust/locustfile.py --worker --master-host master

networks:
  edu:
    # external: true

volumes:
  redis_data:
  mydb: